language: php

php:
- 7.1

services:
- mysql

branches:
  only:
  - master

cache:
    directories:
      - $HOME/.composer/cache

before_install:
- phpenv config-rm xdebug.ini
- cp travis/.env.travis .env
- mysql -e 'create database testing;'
- composer self-update
- composer install --no-interaction --no-suggest
- php artisan key:generate
- php artisan migrate --force

script:
- vendor/bin/phpunit
- php ./travis/coverage-checker.php ./travis/clover.xml 75
